CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL,
    has_electric_vehicle BOOLEAN NOT NULL DEFAULT false
);
INSERT INTO users (email, first_name, last_name, role, has_electric_vehicle) VALUES
('alice.dupont@example.com', 'Alice', 'Dupont', 'EMPLOYEE', true),
('bob.lemoine@example.com', 'Bob', 'Lemoine', 'SECRETARY', true),
('charlie.moreau@example.com', 'Charlie', 'Moreau', 'EMPLOYEE', true),
('diana.bernard@example.com', 'Diana', 'Bernard', 'EMPLOYEE', true),
('eva.petit@example.com', 'Eva', 'Petit', 'EMPLOYEE', true),
('frank.durand@example.com', 'Frank', 'Durand', 'EMPLOYEE', true),
('grace.leroy@example.com', 'Grace', 'Leroy', 'EMPLOYEE', true),
('hugo.simon@example.com', 'Hugo', 'Simon', 'EMPLOYEE', false),
('iris.michel@example.com', 'Iris', 'Michel', 'EMPLOYEE', false),
('jack.garcia@example.com', 'Jack', 'Garcia', 'SECRETARY', true),
('kevin.martinez@example.com', 'Kevin', 'Martinez', 'SECRETARY', true),
('laura.robert@example.com', 'Laura', 'Robert', 'EMPLOYEE', false),
('martin.richard@example.com', 'Martin', 'Richard', 'EMPLOYEE', true),
('nina.henry@example.com', 'Nina', 'Henry', 'MANAGER', false),
('oscar.roux@example.com', 'Oscar', 'Roux', 'EMPLOYEE', false),
('paul.vincent@example.com', 'Paul', 'Vincent', 'EMPLOYEE', false),
('quentin.fabre@example.com', 'Quentin', 'Fabre', 'EMPLOYEE', true),
('rosa.noel@example.com', 'Rosa', 'Noel', 'SECRETARY', true),
('sami.adam@example.com', 'Sami', 'Adam', 'MANAGER', false),
('tina.bonnet@example.com', 'Tina', 'Bonnet', 'EMPLOYEE', false),
('ugo.colin@example.com', 'Ugo', 'Colin', 'SECRETARY', false),
('valerie.gomez@example.com', 'Valerie', 'Gomez', 'EMPLOYEE', true),
('william.dupont@example.com', 'William', 'Dupont', 'EMPLOYEE', true),
('xenia.lemoine@example.com', 'Xenia', 'Lemoine', 'SECRETARY', true),
('yasmine.moreau@example.com', 'Yasmine', 'Moreau', 'SECRETARY', true),
('zack.bernard@example.com', 'Zack', 'Bernard', 'EMPLOYEE', false),
('clara.petit@example.com', 'Clara', 'Petit', 'EMPLOYEE', false),
('david.durand@example.com', 'David', 'Durand', 'EMPLOYEE', false),
('emma.leroy@example.com', 'Emma', 'Leroy', 'EMPLOYEE', false),
('fay.simon@example.com', 'Fay', 'Simon', 'SECRETARY', true),
('gaspard.michel@example.com', 'Gaspard', 'Michel', 'EMPLOYEE', true),
('helene.garcia@example.com', 'Helene', 'Garcia', 'EMPLOYEE', true),
('igor.martinez@example.com', 'Igor', 'Martinez', 'EMPLOYEE', false),
('julia.robert@example.com', 'Julia', 'Robert', 'EMPLOYEE', true),
('kamil.richard@example.com', 'Kamil', 'Richard', 'EMPLOYEE', true),
('lina.henry@example.com', 'Lina', 'Henry', 'EMPLOYEE', true),
('mathieu.roux@example.com', 'Mathieu', 'Roux', 'SECRETARY', false),
('nora.vincent@example.com', 'Nora', 'Vincent', 'EMPLOYEE', true),
('olivier.fabre@example.com', 'Olivier', 'Fabre', 'MANAGER', false),
('patricia.noel@example.com', 'Patricia', 'Noel', 'EMPLOYEE', false),
('luc.adam@example.com', 'Luc', 'Adam', 'EMPLOYEE', false),
('lea.bonnet@example.com', 'Lea', 'Bonnet', 'EMPLOYEE', true),
('marc.colin@example.com', 'Marc', 'Colin', 'EMPLOYEE', false),
('nadia.gomez@example.com', 'Nadia', 'Gomez', 'SECRETARY', false),
('jeremy.dupont@example.com', 'Jeremy', 'Dupont', 'SECRETARY', false),
('ines.lemoine@example.com', 'Ines', 'Lemoine', 'EMPLOYEE', true),
('tristan.moreau@example.com', 'Tristan', 'Moreau', 'EMPLOYEE', true),
('celine.bernard@example.com', 'Celine', 'Bernard', 'SECRETARY', true),
('amelie.petit@example.com', 'Amelie', 'Petit', 'EMPLOYEE', true),
('sebastien.durand@example.com', 'Sebastien', 'Durand', 'SECRETARY', false),
('melanie.leroy@example.com', 'Melanie', 'Leroy', 'EMPLOYEE', false),
('thomas.simon@example.com', 'Thomas', 'Simon', 'EMPLOYEE', false),
('julie.michel@example.com', 'Julie', 'Michel', 'EMPLOYEE', true),
('adrien.garcia@example.com', 'Adrien', 'Garcia', 'EMPLOYEE', true),
('elise.martinez@example.com', 'Elise', 'Martinez', 'EMPLOYEE', false),
('nicolas.robert@example.com', 'Nicolas', 'Robert', 'SECRETARY', false),
('aurelie.richard@example.com', 'Aurelie', 'Richard', 'EMPLOYEE', false),
('vincent.henry@example.com', 'Vincent', 'Henry', 'EMPLOYEE', true),
('mathilde.roux@example.com', 'Mathilde', 'Roux', 'MANAGER', false),
('louis.vincent@example.com', 'Louis', 'Vincent', 'MANAGER', true),
('anais.fabre@example.com', 'Anais', 'Fabre', 'EMPLOYEE', true),
('charles.noel@example.com', 'Charles', 'Noel', 'SECRETARY', false),
('sophie.adam@example.com', 'Sophie', 'Adam', 'SECRETARY', true),
('julien.bonnet@example.com', 'Julien', 'Bonnet', 'EMPLOYEE', true),
('marie.colin@example.com', 'Marie', 'Colin', 'EMPLOYEE', true),
('mehdi.gomez@example.com', 'Mehdi', 'Gomez', 'EMPLOYEE', false),
('lola.dupont@example.com', 'Lola', 'Dupont', 'EMPLOYEE', false),
('rayan.lemoine@example.com', 'Rayan', 'Lemoine', 'SECRETARY', false),
('camille.moreau@example.com', 'Camille', 'Moreau', 'EMPLOYEE', true),
('laurent.bernard@example.com', 'Laurent', 'Bernard', 'SECRETARY', true);